spring:
  config:
    activate.on-profile: prod
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Moscow

---
spring:
  config:
    activate.on-profile: default
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Moscow
