spring:
  config:
    activate.on-profile: prod
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Moscow
#SWAGGER
springdoc:
#  swagger-ui:
#    path: /swagger-ui.html  # This sets the URL to access Swagger UI.
  api-docs:
    path: /v3/api-docs  # This sets the path to the generated OpenAPI documentation.


---
spring:
  config:
    activate.on-profile: default
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Moscow
#SWAGGER
springdoc:
#  swagger-ui:
#    path: /swagger-ui.html  # This sets the URL to access Swagger UI.
  api-docs:
    path: /v3/api-docs  # This sets the path to the generated OpenAPI documentation.

